version: '3.7'

services:
  app:
    build:
      context: ./app
      args:
        app_env: development
    restart: always
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - survey
  db:
    build:
      context: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    container_name: database
    hostname: database
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: survey
      MYSQL_USER: api
      MYSQL_PASSWORD: password
    networks:
      - survey
  api:
    build:
      context: ./api
    restart: always
    volumes:
      - ./api:/app
    ports:
      - "5000:8080"
    environment: 
      DEBUG: "true"          
      # GIN_MODE: "release"  
    links:
      - db
    networks:
      - survey
networks:
  survey:
    driver: bridge